# Generated by Django 4.2.11 on 2025-11-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_ventas_delete_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='alerta', serialize=False, to='stock.producto')),
                ('umbral_minimo', models.PositiveIntegerField(default=5, verbose_name='Umbral Mínimo de Stock')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='umbral_alerta',
            field=models.PositiveIntegerField(default=5, verbose_name='Stock Mínimo de Alerta'),
        ),
    ]
